"""SA-GHMAPPO 主算法。"""

from __future__ import annotations

from src.agents.sa_ghmappo_core import SAGHMAPPOBaseAgent


class SAGHMAPPOAgent(SAGHMAPPOBaseAgent):
    """Surrogate-Assisted Graph Hierarchical Multi-Agent PPO。

    结构要点：
    1. graph / DAG-aware encoder
    2. slow / fast / event 三时间尺度 actor heads
    3. centralized critic
    4. surrogate-assisted prediction confidence / uncertainty gating
    """

    def __init__(
        self,
        use_prediction_features: bool = True,
        use_graph_encoder: bool = True,
        use_hierarchy: bool = True,
        use_event_agent: bool = True,
        use_adapter_prefetch: bool = True,
        use_dependency_aware: bool = True,
        use_uncertainty_signal: bool = True,
        graph_continuity_critic_enabled: bool = False,
        uncertainty_aware_event_scaling_enabled: bool = False,
        uncertainty_aware_critic_enabled: bool = False,
        auxiliary_coef: float = 0.1,
        prediction_gate_min_leak: float = 0.2,
        event_policy_credit_floor: float = 0.15,
        event_advantage_blend: float = 0.85,
        event_entropy_coef_scale: float = 3.5,
        event_entropy_credit_floor: float = 0.35,
        event_logit_temperature: float = 1.4,
        event_logit_temperature_final: float = 0.85,
        event_temperature_decay_updates: int = 8,
        event_logit_sharpening_final_scale: float = 2.3,
        event_logit_sharpening_timing_gain: float = 0.85,
        event_actor_loss_extra_gain: float = 1.25,
        event_prepare_margin_boost: float = 0.35,
        temporal_consistency_coef: float = 0.35,
        temporal_prepare_lead_steps: float = 2.5,
        temporal_prepare_sigma: float = 1.25,
        temporal_prepare_activation_threshold: float = 0.35,
        continuity_guard_enabled: bool = False,
        handoff_target_alignment_guard_enabled: bool = False,
        continuity_guard_logit_penalty: float = 1.0,
        continuity_guard_prepare_boost: float = 1.25,
        continuity_guard_confidence_threshold: float = 0.45,
        continuity_guard_prepare_score_threshold: float = 0.30,
        continuity_guard_hard_override_enabled: bool = False,
        heuristic_imitation_coef: float = 0.0,
        heuristic_imitation_warmup_updates: int = 2,
        heuristic_imitation_decay: float = 0.5,
        mechanism_aux_coef: float = 0.0,
        mechanism_window_weight: float = 1.0,
        prepare_action_prior_weight: float = 0.5,
        mechanism_entropy_coef: float = 0.0,
        mechanism_retention_start_update: int = 0,
        mechanism_aux_coef_floor_after_update: float = 0.0,
        mechanism_window_weight_floor_after_update: float = 1.0,
        mechanism_entropy_floor_after_update: float = 0.0,
        cache_warm_start_guard_enabled: bool = False,
        cache_warm_start_guard_min_countdown: float = 1.5,
        cache_warm_start_guard_max_prefetch_countdown: float = 0.0,
        predictive_prefetch_admission_guard_enabled: bool = False,
        predictive_prefetch_admission_min_confidence: float = 0.55,
        predictive_prefetch_admission_require_distinct_next: bool = True,
        **kwargs,
    ) -> None:
        super().__init__(
            agent_name="sa_ghmappo",
            policy_type="sa_ghmappo_policy",
            encoder_kind="graph" if use_graph_encoder else "flat",
            centralized_critic=True,
            hierarchical_conditioning=bool(use_hierarchy),
            use_hierarchy=bool(use_hierarchy),
            use_prediction_features=bool(use_prediction_features),
            use_uncertainty_signal=bool(use_uncertainty_signal),
            use_dependency_aware=bool(use_dependency_aware),
            graph_continuity_critic_enabled=bool(graph_continuity_critic_enabled),
            uncertainty_aware_event_scaling_enabled=bool(uncertainty_aware_event_scaling_enabled),
            uncertainty_aware_critic_enabled=bool(uncertainty_aware_critic_enabled),
            event_head_enabled=bool(use_event_agent),
            adapter_prefetch_enabled=bool(use_adapter_prefetch),
            auxiliary_coef=auxiliary_coef,
            prediction_gate_min_leak=prediction_gate_min_leak,
            event_policy_credit_floor=event_policy_credit_floor,
            event_advantage_blend=event_advantage_blend,
            event_entropy_coef_scale=event_entropy_coef_scale,
            event_entropy_credit_floor=event_entropy_credit_floor,
            event_logit_temperature=event_logit_temperature,
            event_logit_temperature_final=event_logit_temperature_final,
            event_temperature_decay_updates=event_temperature_decay_updates,
            event_logit_sharpening_final_scale=event_logit_sharpening_final_scale,
            event_logit_sharpening_timing_gain=event_logit_sharpening_timing_gain,
            event_actor_loss_extra_gain=event_actor_loss_extra_gain,
            event_prepare_margin_boost=event_prepare_margin_boost,
            temporal_consistency_coef=temporal_consistency_coef,
            temporal_prepare_lead_steps=temporal_prepare_lead_steps,
            temporal_prepare_sigma=temporal_prepare_sigma,
            temporal_prepare_activation_threshold=temporal_prepare_activation_threshold,
            continuity_guard_enabled=continuity_guard_enabled,
            handoff_target_alignment_guard_enabled=handoff_target_alignment_guard_enabled,
            continuity_guard_logit_penalty=continuity_guard_logit_penalty,
            continuity_guard_prepare_boost=continuity_guard_prepare_boost,
            continuity_guard_confidence_threshold=continuity_guard_confidence_threshold,
            continuity_guard_prepare_score_threshold=continuity_guard_prepare_score_threshold,
            continuity_guard_hard_override_enabled=continuity_guard_hard_override_enabled,
            heuristic_imitation_coef=heuristic_imitation_coef,
            heuristic_imitation_warmup_updates=heuristic_imitation_warmup_updates,
            heuristic_imitation_decay=heuristic_imitation_decay,
            mechanism_aux_coef=mechanism_aux_coef,
            mechanism_window_weight=mechanism_window_weight,
            prepare_action_prior_weight=prepare_action_prior_weight,
            mechanism_entropy_coef=mechanism_entropy_coef,
            mechanism_retention_start_update=mechanism_retention_start_update,
            mechanism_aux_coef_floor_after_update=mechanism_aux_coef_floor_after_update,
            mechanism_window_weight_floor_after_update=mechanism_window_weight_floor_after_update,
            mechanism_entropy_floor_after_update=mechanism_entropy_floor_after_update,
            cache_warm_start_guard_enabled=cache_warm_start_guard_enabled,
            cache_warm_start_guard_min_countdown=cache_warm_start_guard_min_countdown,
            cache_warm_start_guard_max_prefetch_countdown=cache_warm_start_guard_max_prefetch_countdown,
            predictive_prefetch_admission_guard_enabled=predictive_prefetch_admission_guard_enabled,
            predictive_prefetch_admission_min_confidence=predictive_prefetch_admission_min_confidence,
            predictive_prefetch_admission_require_distinct_next=predictive_prefetch_admission_require_distinct_next,
            **kwargs,
        )
        self.ablation_config = {
            "use_prediction_features": bool(use_prediction_features),
            "use_graph_encoder": bool(use_graph_encoder),
            "use_hierarchy": bool(use_hierarchy),
            "use_event_agent": bool(use_event_agent),
            "use_adapter_prefetch": bool(use_adapter_prefetch),
            "use_dependency_aware": bool(use_dependency_aware),
            "use_uncertainty_signal": bool(use_uncertainty_signal),
            "graph_continuity_critic_enabled": bool(graph_continuity_critic_enabled),
            "uncertainty_aware_event_scaling_enabled": bool(uncertainty_aware_event_scaling_enabled),
            "uncertainty_aware_critic_enabled": bool(uncertainty_aware_critic_enabled),
            "prediction_gate_min_leak": float(prediction_gate_min_leak),
            "event_policy_credit_floor": float(event_policy_credit_floor),
            "event_advantage_blend": float(event_advantage_blend),
            "event_entropy_coef_scale": float(event_entropy_coef_scale),
            "event_entropy_credit_floor": float(event_entropy_credit_floor),
            "event_logit_temperature": float(event_logit_temperature),
            "event_logit_temperature_final": float(event_logit_temperature_final),
            "event_temperature_decay_updates": int(event_temperature_decay_updates),
            "event_logit_sharpening_final_scale": float(event_logit_sharpening_final_scale),
            "event_logit_sharpening_timing_gain": float(event_logit_sharpening_timing_gain),
            "event_actor_loss_extra_gain": float(event_actor_loss_extra_gain),
            "event_prepare_margin_boost": float(event_prepare_margin_boost),
            "temporal_consistency_coef": float(temporal_consistency_coef),
            "temporal_prepare_lead_steps": float(temporal_prepare_lead_steps),
            "temporal_prepare_sigma": float(temporal_prepare_sigma),
            "temporal_prepare_activation_threshold": float(temporal_prepare_activation_threshold),
            "continuity_guard_enabled": bool(continuity_guard_enabled),
            "handoff_target_alignment_guard_enabled": bool(handoff_target_alignment_guard_enabled),
            "continuity_guard_logit_penalty": float(continuity_guard_logit_penalty),
            "continuity_guard_prepare_boost": float(continuity_guard_prepare_boost),
            "continuity_guard_confidence_threshold": float(continuity_guard_confidence_threshold),
            "continuity_guard_prepare_score_threshold": float(continuity_guard_prepare_score_threshold),
            "continuity_guard_hard_override_enabled": bool(continuity_guard_hard_override_enabled),
            "heuristic_imitation_coef": float(heuristic_imitation_coef),
            "heuristic_imitation_warmup_updates": int(heuristic_imitation_warmup_updates),
            "heuristic_imitation_decay": float(heuristic_imitation_decay),
            "mechanism_aux_coef": float(mechanism_aux_coef),
            "mechanism_window_weight": float(mechanism_window_weight),
            "prepare_action_prior_weight": float(prepare_action_prior_weight),
            "mechanism_entropy_coef": float(mechanism_entropy_coef),
            "mechanism_retention_start_update": int(mechanism_retention_start_update),
            "mechanism_aux_coef_floor_after_update": float(mechanism_aux_coef_floor_after_update),
            "mechanism_window_weight_floor_after_update": float(mechanism_window_weight_floor_after_update),
            "mechanism_entropy_floor_after_update": float(mechanism_entropy_floor_after_update),
            "cache_warm_start_guard_enabled": bool(cache_warm_start_guard_enabled),
            "cache_warm_start_guard_min_countdown": float(cache_warm_start_guard_min_countdown),
            "cache_warm_start_guard_max_prefetch_countdown": float(
                cache_warm_start_guard_max_prefetch_countdown
            ),
            "predictive_prefetch_admission_guard_enabled": bool(
                predictive_prefetch_admission_guard_enabled
            ),
            "predictive_prefetch_admission_min_confidence": float(
                predictive_prefetch_admission_min_confidence
            ),
            "predictive_prefetch_admission_require_distinct_next": bool(
                predictive_prefetch_admission_require_distinct_next
            ),
        }
        for field_name in (
            "net_utility_prd_enabled",
            "net_utility_backhaul_coef",
            "net_utility_migration_coef",
            "net_utility_expired_prefetch_coef",
            "net_utility_idle_prefetch_penalty",
            "net_utility_success_bonus",
            "net_utility_backhaul_normalizer",
            "net_utility_cost_dual_enabled",
            "net_utility_cost_dual_lr",
            "net_utility_cost_target",
            "net_utility_cost_dual_max",
            "net_utility_cost_dual_initial",
            "net_utility_option_termination_enabled",
            "net_utility_option_termination_conservative_enabled",
            "net_utility_option_termination_max_timing_support",
            "net_advantage_prepare_gate_enabled",
            "net_advantage_prepare_gate_bias",
            "net_advantage_prepare_gate_min_score",
            "net_advantage_prepare_gate_margin",
            "net_advantage_prepare_gate_prefetch_scale",
            "net_advantage_prepare_gate_current_scale",
            "net_advantage_prepare_gate_service_fill_scale",
            "net_advantage_prepare_gate_local_penalty_scale",
            "net_advantage_prepare_gate_cost_scale",
            "net_advantage_prepare_gate_policy_coef",
            "net_advantage_prepare_gate_event_coef",
            "net_advantage_prepare_gate_clip",
            "coverage_recovery_gate_bias_scale",
            "coverage_recovery_gate_min_scale",
            "coverage_recovery_gate_fallback_suppression_scale",
            "coverage_recovery_gate_fast_suppression_scale",
            "coverage_recovery_gate_current_suppression_scale",
            "coverage_recovery_gate_prepare_credit",
            "coverage_recovery_gate_fallback_penalty",
            "coverage_recovery_guard_enabled",
            "coverage_recovery_final_guard_enabled",
            "coverage_recovery_final_guard_min_scale",
            "coverage_recovery_final_guard_min_confidence",
            "coverage_recovery_target_memory_option_credit",
            "coverage_recovery_target_memory_option_penalty",
            "opportunity_constrained_no_rsu_service_bias",
            "opportunity_constrained_no_rsu_local_penalty",
            "opportunity_constrained_no_rsu_prepare_bias",
            "opportunity_constrained_no_rsu_prepare_min_context",
            "idle_popularity_no_rsu_service_continuity_enabled",
            "idle_popularity_no_rsu_any_action_override_enabled",
            "option_gate_idle_recovery_mechanism_prior_enabled",
            "option_gate_idle_recovery_min_context",
            "service_continuity_teacher_enabled",
            "service_continuity_current_bonus",
            "service_continuity_prepare_bonus",
            "service_continuity_local_penalty",
            "service_continuity_min_prepare_context",
            "service_completion_gate_enabled",
            "service_completion_gate_bias",
            "service_completion_gate_remaining_nodes_threshold",
            "service_completion_gate_event_suppression_scale",
            "service_completion_gate_prefetch_suppression_scale",
            "service_completion_gate_fallback_suppression_scale",
            "service_completion_gate_policy_coef",
            "service_completion_gate_event_coef",
            "service_completion_gate_clip",
            "retrospective_handoff_aux_enabled",
            "retrospective_handoff_aux_max_eta",
            "retrospective_handoff_aux_min_score",
            "retrospective_handoff_aux_prepare_weight",
            "retrospective_handoff_aux_transition_weight",
            "backhaul_aware_policy_enabled",
            "backhaul_aware_service_fill_bias",
            "backhaul_aware_redundant_fill_penalty",
            "backhaul_aware_no_signal_prefetch_penalty",
            "backhaul_aware_no_signal_prepare_penalty",
            "backhaul_aware_steady_bias",
            "backhaul_aware_service_pressure_floor",
            "dag_aware_option_termination_enabled",
            "dag_aware_option_min_critical_path",
            "dag_aware_option_short_workflow_max_nodes",
            "dag_aware_option_branching_successors",
            "dag_aware_idle_prefetch_confidence_floor",
            "option_gate_counterfactual_prd_enabled",
            "option_gate_counterfactual_coef",
            "option_gate_counterfactual_clip",
            "handoff_risk_prd_enabled",
            "handoff_risk_event_coef",
            "handoff_risk_option_coef",
            "handoff_risk_clip",
            "handoff_risk_failure_penalty",
            "handoff_risk_ready_bonus",
            "handoff_risk_prepare_bonus",
            "handoff_risk_unprepared_penalty",
            "handoff_risk_confidence_threshold",
            "handoff_risk_cost_dual_enabled",
            "handoff_risk_cost_dual_lr",
            "handoff_risk_cost_target",
            "handoff_risk_cost_dual_max",
            "handoff_risk_cost_dual_initial",
            "idle_execution_prd_enabled",
            "idle_execution_policy_coef",
            "idle_execution_option_coef",
            "idle_execution_clip",
            "idle_execution_current_rsu_delay_coef",
            "idle_execution_local_bonus",
            "idle_execution_mechanism_penalty",
            "idle_execution_timing_threshold",
            "idle_execution_mechanism_preserve_bonus",
            "env_action_ppo_enabled",
            "env_action_ppo_coef",
            "env_action_ppo_teacher_coef",
            "env_action_ppo_mechanism_focus",
            "env_action_sparse_recovery_focus",
            "env_action_risk_adjusted_recovery_coef",
            "env_action_risk_adjusted_recovery_floor",
            "env_action_adapter_miss_counterfactual_coef",
            "cache_feasibility_prior_enabled",
            "cache_feasibility_cache_fill_bias",
            "cache_feasibility_steady_penalty",
            "cache_feasibility_prepare_penalty",
            "cache_feasibility_prefetch_penalty",
            "cache_feasibility_current_miss_prepare_penalty",
            "cache_feasibility_current_miss_prefetch_penalty",
            "cache_feasibility_min_context",
            "handoff_alignment_barrier_enabled",
            "handoff_alignment_barrier_prepare_penalty",
            "handoff_alignment_barrier_prefetch_penalty",
            "handoff_alignment_barrier_current_fill_bias",
            "handoff_alignment_barrier_target_mismatch_penalty",
            "handoff_alignment_barrier_late_eta_penalty",
            "handoff_alignment_barrier_min_context",
            "sparse_handoff_recovery_prior_enabled",
            "sparse_handoff_recovery_prefetch_bias",
            "sparse_handoff_recovery_prepare_bias",
            "sparse_handoff_recovery_current_fill_bias",
            "sparse_handoff_recovery_steady_bias",
            "sparse_handoff_recovery_local_penalty",
            "sparse_handoff_recovery_min_context",
            "sparse_handoff_recovery_max_eta",
            "sparse_handoff_realization_credit_enabled",
            "sparse_handoff_realization_success_bonus",
            "sparse_handoff_realization_ready_bonus",
            "sparse_handoff_realization_prefetch_bonus",
            "sparse_handoff_realization_failed_prepare_penalty",
            "sparse_handoff_realization_local_penalty",
            "sparse_handoff_realization_min_context",
            "sparse_handoff_option_prior_enabled",
            "sparse_handoff_option_prepare_bias",
            "sparse_handoff_option_popularity_penalty",
            "sparse_handoff_option_local_penalty",
            "sparse_handoff_option_min_context",
            "sparse_handoff_option_max_eta",
            "env_action_counterfactual_margin_enabled",
            "env_action_counterfactual_margin_coef",
            "env_action_counterfactual_margin_max_weight",
            "argmax_margin_regularization_enabled",
            "argmax_margin_coef",
            "argmax_margin_min_gap",
            "argmax_margin_max_weight",
            "argmax_margin_tail_risk_threshold",
            "argmax_margin_mechanism_penalty_scale",
            "counterfactual_teacher_prd_enabled",
            "counterfactual_teacher_option_coef",
        ):
            if field_name in kwargs:
                self.ablation_config[field_name] = kwargs[field_name]
