"""SA-GHMAPPO 主算法。"""

from __future__ import annotations

from src.agents.sa_ghmappo_core import SAGHMAPPOBaseAgent


class SAGHMAPPOAgent(SAGHMAPPOBaseAgent):
    """Surrogate-Assisted Graph Hierarchical Multi-Agent PPO。

    结构要点：
    1. graph / DAG-aware encoder
    2. slow / fast / event 三时间尺度 actor heads
    3. centralized critic
    4. surrogate-assisted prediction confidence / uncertainty gating
    """

    def __init__(
        self,
        use_prediction_features: bool = True,
        use_graph_encoder: bool = True,
        use_hierarchy: bool = True,
        use_event_agent: bool = True,
        use_adapter_prefetch: bool = True,
        use_dependency_aware: bool = True,
        use_uncertainty_signal: bool = True,
        graph_continuity_critic_enabled: bool = False,
        uncertainty_aware_event_scaling_enabled: bool = False,
        uncertainty_aware_critic_enabled: bool = False,
        auxiliary_coef: float = 0.1,
        prediction_gate_min_leak: float = 0.2,
        event_policy_credit_floor: float = 0.15,
        event_advantage_blend: float = 0.85,
        event_entropy_coef_scale: float = 3.5,
        event_entropy_credit_floor: float = 0.35,
        event_logit_temperature: float = 1.4,
        event_logit_temperature_final: float = 0.85,
        event_temperature_decay_updates: int = 8,
        event_logit_sharpening_final_scale: float = 2.3,
        event_logit_sharpening_timing_gain: float = 0.85,
        event_actor_loss_extra_gain: float = 1.25,
        event_prepare_margin_boost: float = 0.35,
        temporal_consistency_coef: float = 0.35,
        temporal_prepare_lead_steps: float = 2.5,
        temporal_prepare_sigma: float = 1.25,
        temporal_prepare_activation_threshold: float = 0.35,
        continuity_guard_enabled: bool = False,
        handoff_target_alignment_guard_enabled: bool = False,
        continuity_guard_logit_penalty: float = 1.0,
        continuity_guard_prepare_boost: float = 1.25,
        continuity_guard_confidence_threshold: float = 0.45,
        continuity_guard_prepare_score_threshold: float = 0.30,
        continuity_guard_hard_override_enabled: bool = False,
        heuristic_imitation_coef: float = 0.0,
        heuristic_imitation_warmup_updates: int = 2,
        heuristic_imitation_decay: float = 0.5,
        mechanism_aux_coef: float = 0.0,
        mechanism_window_weight: float = 1.0,
        prepare_action_prior_weight: float = 0.5,
        mechanism_entropy_coef: float = 0.0,
        mechanism_retention_start_update: int = 0,
        mechanism_aux_coef_floor_after_update: float = 0.0,
        mechanism_window_weight_floor_after_update: float = 1.0,
        mechanism_entropy_floor_after_update: float = 0.0,
        cache_warm_start_guard_enabled: bool = False,
        cache_warm_start_guard_min_countdown: float = 1.5,
        cache_warm_start_guard_max_prefetch_countdown: float = 0.0,
        **kwargs,
    ) -> None:
        super().__init__(
            agent_name="sa_ghmappo",
            policy_type="sa_ghmappo_policy",
            encoder_kind="graph" if use_graph_encoder else "flat",
            centralized_critic=True,
            hierarchical_conditioning=bool(use_hierarchy),
            use_hierarchy=bool(use_hierarchy),
            use_prediction_features=bool(use_prediction_features),
            use_uncertainty_signal=bool(use_uncertainty_signal),
            use_dependency_aware=bool(use_dependency_aware),
            graph_continuity_critic_enabled=bool(graph_continuity_critic_enabled),
            uncertainty_aware_event_scaling_enabled=bool(uncertainty_aware_event_scaling_enabled),
            uncertainty_aware_critic_enabled=bool(uncertainty_aware_critic_enabled),
            event_head_enabled=bool(use_event_agent),
            adapter_prefetch_enabled=bool(use_adapter_prefetch),
            auxiliary_coef=auxiliary_coef,
            prediction_gate_min_leak=prediction_gate_min_leak,
            event_policy_credit_floor=event_policy_credit_floor,
            event_advantage_blend=event_advantage_blend,
            event_entropy_coef_scale=event_entropy_coef_scale,
            event_entropy_credit_floor=event_entropy_credit_floor,
            event_logit_temperature=event_logit_temperature,
            event_logit_temperature_final=event_logit_temperature_final,
            event_temperature_decay_updates=event_temperature_decay_updates,
            event_logit_sharpening_final_scale=event_logit_sharpening_final_scale,
            event_logit_sharpening_timing_gain=event_logit_sharpening_timing_gain,
            event_actor_loss_extra_gain=event_actor_loss_extra_gain,
            event_prepare_margin_boost=event_prepare_margin_boost,
            temporal_consistency_coef=temporal_consistency_coef,
            temporal_prepare_lead_steps=temporal_prepare_lead_steps,
            temporal_prepare_sigma=temporal_prepare_sigma,
            temporal_prepare_activation_threshold=temporal_prepare_activation_threshold,
            continuity_guard_enabled=continuity_guard_enabled,
            handoff_target_alignment_guard_enabled=handoff_target_alignment_guard_enabled,
            continuity_guard_logit_penalty=continuity_guard_logit_penalty,
            continuity_guard_prepare_boost=continuity_guard_prepare_boost,
            continuity_guard_confidence_threshold=continuity_guard_confidence_threshold,
            continuity_guard_prepare_score_threshold=continuity_guard_prepare_score_threshold,
            continuity_guard_hard_override_enabled=continuity_guard_hard_override_enabled,
            heuristic_imitation_coef=heuristic_imitation_coef,
            heuristic_imitation_warmup_updates=heuristic_imitation_warmup_updates,
            heuristic_imitation_decay=heuristic_imitation_decay,
            mechanism_aux_coef=mechanism_aux_coef,
            mechanism_window_weight=mechanism_window_weight,
            prepare_action_prior_weight=prepare_action_prior_weight,
            mechanism_entropy_coef=mechanism_entropy_coef,
            mechanism_retention_start_update=mechanism_retention_start_update,
            mechanism_aux_coef_floor_after_update=mechanism_aux_coef_floor_after_update,
            mechanism_window_weight_floor_after_update=mechanism_window_weight_floor_after_update,
            mechanism_entropy_floor_after_update=mechanism_entropy_floor_after_update,
            cache_warm_start_guard_enabled=cache_warm_start_guard_enabled,
            cache_warm_start_guard_min_countdown=cache_warm_start_guard_min_countdown,
            cache_warm_start_guard_max_prefetch_countdown=cache_warm_start_guard_max_prefetch_countdown,
            **kwargs,
        )
        self.ablation_config = {
            "use_prediction_features": bool(use_prediction_features),
            "use_graph_encoder": bool(use_graph_encoder),
            "use_hierarchy": bool(use_hierarchy),
            "use_event_agent": bool(use_event_agent),
            "use_adapter_prefetch": bool(use_adapter_prefetch),
            "use_dependency_aware": bool(use_dependency_aware),
            "use_uncertainty_signal": bool(use_uncertainty_signal),
            "graph_continuity_critic_enabled": bool(graph_continuity_critic_enabled),
            "uncertainty_aware_event_scaling_enabled": bool(uncertainty_aware_event_scaling_enabled),
            "uncertainty_aware_critic_enabled": bool(uncertainty_aware_critic_enabled),
            "prediction_gate_min_leak": float(prediction_gate_min_leak),
            "event_policy_credit_floor": float(event_policy_credit_floor),
            "event_advantage_blend": float(event_advantage_blend),
            "event_entropy_coef_scale": float(event_entropy_coef_scale),
            "event_entropy_credit_floor": float(event_entropy_credit_floor),
            "event_logit_temperature": float(event_logit_temperature),
            "event_logit_temperature_final": float(event_logit_temperature_final),
            "event_temperature_decay_updates": int(event_temperature_decay_updates),
            "event_logit_sharpening_final_scale": float(event_logit_sharpening_final_scale),
            "event_logit_sharpening_timing_gain": float(event_logit_sharpening_timing_gain),
            "event_actor_loss_extra_gain": float(event_actor_loss_extra_gain),
            "event_prepare_margin_boost": float(event_prepare_margin_boost),
            "temporal_consistency_coef": float(temporal_consistency_coef),
            "temporal_prepare_lead_steps": float(temporal_prepare_lead_steps),
            "temporal_prepare_sigma": float(temporal_prepare_sigma),
            "temporal_prepare_activation_threshold": float(temporal_prepare_activation_threshold),
            "continuity_guard_enabled": bool(continuity_guard_enabled),
            "handoff_target_alignment_guard_enabled": bool(handoff_target_alignment_guard_enabled),
            "continuity_guard_logit_penalty": float(continuity_guard_logit_penalty),
            "continuity_guard_prepare_boost": float(continuity_guard_prepare_boost),
            "continuity_guard_confidence_threshold": float(continuity_guard_confidence_threshold),
            "continuity_guard_prepare_score_threshold": float(continuity_guard_prepare_score_threshold),
            "continuity_guard_hard_override_enabled": bool(continuity_guard_hard_override_enabled),
            "heuristic_imitation_coef": float(heuristic_imitation_coef),
            "heuristic_imitation_warmup_updates": int(heuristic_imitation_warmup_updates),
            "heuristic_imitation_decay": float(heuristic_imitation_decay),
            "mechanism_aux_coef": float(mechanism_aux_coef),
            "mechanism_window_weight": float(mechanism_window_weight),
            "prepare_action_prior_weight": float(prepare_action_prior_weight),
            "mechanism_entropy_coef": float(mechanism_entropy_coef),
            "mechanism_retention_start_update": int(mechanism_retention_start_update),
            "mechanism_aux_coef_floor_after_update": float(mechanism_aux_coef_floor_after_update),
            "mechanism_window_weight_floor_after_update": float(mechanism_window_weight_floor_after_update),
            "mechanism_entropy_floor_after_update": float(mechanism_entropy_floor_after_update),
            "cache_warm_start_guard_enabled": bool(cache_warm_start_guard_enabled),
            "cache_warm_start_guard_min_countdown": float(cache_warm_start_guard_min_countdown),
            "cache_warm_start_guard_max_prefetch_countdown": float(
                cache_warm_start_guard_max_prefetch_countdown
            ),
        }
